{% set name = "jupyterlite-xeus" %}
{% set version = "4.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jupyterlite_xeus-{{ version }}.tar.gz
  sha256: df8f1e52dc4328e5efbdf0eaf885fe5b80ab730df51591af030b20003bf45b9e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - jupyterlab >=3,<5
    - empack >=5.1.1,<7
    - hatchling
    - hatch-jupyter-builder
    - hatch-nodejs-version
  run:
    - python >={{ python_min }}
    - empack >=5.1.1,<7
    - traitlets
    - jupyterlite-core >=0.7,<0.8
    - pyyaml
    - requests
    # This is a hard-dependency now (cannot be for PyPi)
    # https://github.com/jupyterlite/xeus/issues/248 for the hard pin
    - micromamba =2.0.5

test:
  imports:
    - jupyterlite_xeus
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - test -f ${PREFIX}/share/jupyter/labextensions/@jupyterlite/xeus/package.json                            # [unix]
    - if not exist %PREFIX%\\share\\jupyter\\labextensions\\@jupyterlite/xeus\\package.json (exit 1)          # [win]

about:
  home: https://github.com/jupyterlite/xeus
  summary: JupyterLite loader for Xeus kernels
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/jupyterlite/xeus

extra:
  recipe-maintainers:
    - martinRenou
    - trungleduc
