{% set name = "jupyterlite-xeus" %}
{% set version = "3.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jupyterlite_xeus-{{ version }}.tar.gz
  sha256: 9d065b09b5e93ccf02fadc6d9033abf05e6ec0eb8c7ce4a5b169466dab502a9b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - jupyterlab >=3,<4
    - empack >=3.1,<6
    - hatchling
    - hatch-jupyter-builder
    - hatch-nodejs-version
  run:
    - python >={{ python_min }}
    - empack >=4.0.2,<6
    - traitlets
    - jupyterlite-core >=0.1,<0.6
    - pyyaml
    - requests

test:
  imports:
    - jupyterlite_xeus
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - test -f ${PREFIX}/share/jupyter/labextensions/@jupyterlite/xeus/package.json                            # [unix]
    - if not exist %PREFIX%\\share\\jupyter\\labextensions\\@jupyterlite/xeus\\package.json (exit 1)          # [win]

about:
  home: https://github.com/jupyterlite/xeus
  summary: JupyterLite loader for Xeus kernels
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/jupyterlite/xeus

extra:
  recipe-maintainers:
    - martinRenou
    - trungleduc
