{% set name = "jupyterlite-xeus" %}
{% set version = "3.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jupyterlite_xeus-{{ version }}.tar.gz
  sha256: 144696a22e1f30404540f00fcbc0a59e685f36a5f90c7daead69aa2b59547249

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - jupyterlab >=3,<4
    - empack >=3.1,<6
    - hatchling
    - hatch-jupyter-builder
    - hatch-nodejs-version
  run:
    - python >=3.8
    - empack >=4.0.2,<6
    - traitlets
    - jupyterlite-core >=0.1,<0.5
    - pyyaml
    - requests

test:
  imports:
    - jupyterlite_xeus
  requires:
    - pip
  commands:
    - pip check
    - test -f ${PREFIX}/share/jupyter/labextensions/@jupyterlite/xeus/package.json                            # [unix]
    - if not exist %PREFIX%\\share\\jupyter\\labextensions\\@jupyterlite/xeus\\package.json (exit 1)          # [win]

about:
  home: https://github.com/jupyterlite/xeus
  summary: JupyterLite loader for Xeus kernels
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/jupyterlite/xeus

extra:
  recipe-maintainers:
    - martinRenou
    - trungleduc
